stages:
  - build
  # - test
  - deploy

.build-tags:
  tags:
    - bcs
    - dockfather
    - docker

# .test-tags:
#   tags:
#     - bcs
#     - dockfather
#     - dev

.deploy-tags:
  tags:
    - bcs
    - dockfather
    - shell

.dev-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'

.prod-rules:
  rules:
    - if: $CI_COMMIT_TAG

.build-dev-script:
  script:
    - docker buildx build -t borg:dev .

.deploy-dev-script:
  script:
    - docker run
      -d
      -p $HOST_PORT:22
      --restart=unless-stopped
      --name borg
      --device /dev/fuse
      --cap-add SYS_ADMIN
      -e S3_KEY=$S3_DEV_KEY
      -e S3_SECRET=$S3_DEV_SECRET
      -e S3_URL=$S3_DEV_URL
      -e BUCKET_NAME=$S3_DEV_BUCKET
      -e SSH_KEY=$SSH_KEY
      borg:dev

.build-script:
  script:
    - docker buildx build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE:latest .

.deploy-script:
  script:
    - docker run \
      -p $HOST_PORT:22 \
      -d \
      --restart=unless-stopped \
      --name borg \
      --device /dev/fuse \
      --cap-add SYS_ADMIN \
      -e S3_KEY=$S3_KEY \
      -e S3_SECRET=$S3_SECRET \
      -e S3_URL=$S3_URL \
      -e BUCKET_NAME=$S3_BUCKET \
      -e SSH_KEY=$SSH_KEY \
      borg

.before-script:
  before_script:
    - - apk add --no-cache docker

build-dev:
  stage: build
  image: docker:25
  services:
    - docker:dind
  extends:
    - .build-tags
    - .dev-rules
    - .build-dev-script

deploy-dev:
  stage: deploy
  # image: docker:25
  services:
    - docker:dind
  extends:
    - .deploy-tags
    - .dev-rules
    - .before-script
    - .deploy-dev-script

build:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  extends:
    - .build-tags
    - .prod-rules
    - .build-script

deploy:
  stage: deploy
  image: docker:20.10
  services:
    - docker:dind
  extends:
    - .deploy-tags
    - .prod-rules
    - .deploy-script
