stages:
  - build
  # - test
  - release

.build-tags:
  tags:
    - bcs
    - dockfather
    - docker

# .test-tags:
#   tags:
#     - bcs
#     - dockfather
#     - dev

.release-tags:
  tags:
    - bcs
    - dockfather
    - docker

.dev-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'

.release-rules:
  rules:
    - if: $CI_COMMIT_TAG

.release-script:
  script:
    - docker buildx build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE:latest --platform=linux/amd64,linux/arm64 --push .
# services:
#   - docker:dind
.dev-script:
  script:
    - docker buildx build -t $CI_REGISTRY_IMAGE:latest --platform=linux/amd64,linux/arm64 .

build-dev:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  extends:
    - .build-tags
    - .release-rules

release-dev:
  stage: release
  image: docker:20.10
  services:
    - docker:dind
  extends:
    - .release-tags
    - .release-rules

build:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  extends:
    - .build-tags
    - .release-rules

release:
  stage: release
  image: docker:20.10
  services:
    - docker:dind
  extends:
    - .release-tags
    - .release-rules
