stages:
  - build
  # - test
  - release

.build-tags:
  tags:
    - bcs
    - dockfather
    - docker

# .test-tags:
#   tags:
#     - bcs
#     - dockfather
#     - dev

.release-tags:
  tags:
    - bcs
    - dockfather
    - docker

.dev-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'

.release-rules:
  rules:
    - if: $CI_COMMIT_TAG

# services:
#   - docker:dind

build:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  extends:
    - .build-tags
    - .dev-rules

release:
  stage: release
  image: docker:20.10
  services:
    - docker:dind
  extends:
    - .release-tags
    - .release-rules
